spring:
    application:
        name: graduacao
    main:
        banner-mode: off
    datasource:
        url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/graduacao}
        username: ${SPRING_DATASOURCE_USERNAME:graduacao}
        password: ${SPRING_DATASOURCE_PASSWORD:graduacao}
    jpa:
        hibernate:
            ddl-auto: update